import React, { createContext, useContext, useState } from "react";

type Language = "en" | "ru" | "de" | "pl";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navigation
    home: "Home",
    studio: "Studio",
    docs: "Documentation",
    login: "Login",
    logout: "Logout",
    profile: "Profile",
    
    // Home page
    heroTitle: "Turn Competitor Ads Into Your Winners",
    heroSubtitle: "Import proven ads, overlay your product, generate variants. Skip the guesswork, launch what works.",
    getStarted: "Get Started",
    howItWorks: "How It Works",
    step1Title: "Import Competitor Ads",
    step1Desc: "Paste Facebook Ad Library URLs to scrape successful campaigns",
    step2Title: "Upload Your Product",
    step2Desc: "Drop in your product images to replace competitor items",
    step3Title: "Generate Variants",
    step3Desc: "AI creates multiple ad variations instantly",
    whyDifferent: "Why Different",
    whyDifferentDesc: "Most tools start from scratch. We start from what already converts.",
    traditionalTools: "Traditional Tools",
    copyAdd: "COPY ADD",
    traditional1: "Start with blank canvas",
    traditional2: "Guess what works",
    traditional3: "Test everything",
    copyAdd1: "Start with proven ads",
    copyAdd2: "Know what converts",
    copyAdd3: "Iterate winners",
    
    // Auth
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    passwordPlaceholder: "Minimum 6 characters",
    confirmPasswordPlaceholder: "Repeat password",
    demoLogin: "Demo Login",
    noAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    createAccount: "Create Account",
    signupDesc: "Sign up to access COPY ADD",
    signup: "Sign Up",
    signingUp: "Signing up...",
    signupSuccess: "Check your email for verification code",
    signupError: "Registration Error",
    signupFailed: "Failed to sign up",
    loginSuccess: "Successfully logged in",
    passwordsDontMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    invalidEmail: "Please enter a valid email",
    fillAllFields: "Please fill all fields",
    error: "Error",
    success: "Success",
    continueWithGoogle: "Continue with Google",
    googleLoginError: "Failed to login with Google",
    
    // Verify Email
    verifyEmail: "Verify Email",
    verifyEmailDesc: "Enter the 6-digit code sent to",
    verificationCode: "Verification Code",
    verify: "Verify",
    verifying: "Verifying...",
    emailVerified: "Email verified",
    verificationError: "Verification Error",
    invalidCode: "Invalid code",
    enter6DigitCode: "Enter 6-digit code",
    verificationCodeSent: "Verification code sent to email",
    resendCode: "Resend Code",
    codeSent: "Code Sent",
    checkEmail: "Check your email",
    backToLogin: "Back to Login",
    backToStudio: "Back to Studio",
    
    // Studio
    importAds: "Import Competitor Ads",
    importAdsDesc: "Paste Facebook Ad Library URLs or profile links",
    pasteAdUrls: "Paste Facebook Ad Library URLs or profile links",
    chooseFromHistory: "Choose from history",
    noPreviousImports: "No previous imports",
    analyzingAds: "Analyzing competitor ads...",
    authRequired: "Authentication Required",
    authRequiredDesc: "Please log in to access the studio",
    loggedOut: "Logged Out",
    loggedOutDesc: "You have been logged out",
    or: "or",
    
    // Profile
    balance: "Balance",
    username: "Username",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    saveChanges: "Save Changes",
    changeAvatar: "Change Avatar",
    referralCode: "Your Referral Code",
    referralDesc: "Share this code for 25% discount",
    copyCode: "Copy Code",
    codeCopied: "Code copied!",
    settings: "Settings",
    editProfile: "Edit Profile",
    usernameExists: "Username already taken",
    usernameUpdated: "Username updated successfully",
    passwordUpdated: "Password updated successfully",
    avatarUpdated: "Avatar updated successfully",
    
    // Footer
    privacy: "Privacy",
    terms: "Terms",
    
    // Settings
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    lightTheme: "Light",
    darkTheme: "Dark",
    systemTheme: "System",
    snakeGame: "Snake Animation",
    enableSnake: "Enable retro snake animation",
    
    // Studio specific
    competitorAds: "Competitor Ads",
    scrapingCompetitorAds: "Scraping competitor ads...",
    adsImported: "Ads imported",
    successfullyScraped: "Successfully scraped",
    competitorAdsCount: "competitor ads",
    uploadComplete: "Upload complete",
    productsAdded: "product(s) added",
    generatingVariants: "Generating variants",
    aiCreatingVariations: "AI is creating your ad variations...",
    addProduct: "Add Product",
    dragDropOrClick: "Drag & drop or click",
    dropHere: "Drop here",
    generate: "Generate with AI",
    import: "Import",
    importLink: "Import Link",
    importLinkDesc: "Add a new link for scraping competitor ads",
    importUrlPlaceholder: "Enter competitor ad URL",
    cancel: "Cancel",
    enterPrompt: "Write your prompt",
    selectAll: "Select All",
    selected: "Selected",
    toPhotos: "to photos",
    toAllPhotos: "to all photos",
    describeChanges: "Describe changes...",
    clear: "Clear",
    
    // Photo Editor
    photoEditor: "Photo Editor",
    promptForThisPhoto: "Prompt for this photo",
    describeChangesForPhoto: "Describe changes for this photo...",
    imageSettings: "Image Settings",
    brightness: "Brightness",
    contrast: "Contrast",
    saturation: "Saturation",
    reset: "Reset",
    done: "Done",
    characters: "characters",
    
    // Home page stats
    activeUsers: "Active Users",
    adsCreated: "Ads Created",
    successRate: "Success Rate",
    
    // Photo History
    photoHistory: "Photo History",
    photoHistoryDesc: "Select a photo from your history or upload a new one",
    historyEmpty: "History is empty",
    historyEmptyDesc: "Upload your first photo to get started",
    selectPhoto: "Select",
    deletePhoto: "Delete",
    photoSelected: "Photo selected",
    photoAddedToProject: "added to project",
    photoDeleted: "Photo deleted",
    failedToDeletePhotos: "Failed to delete photos",
    failedToLoadPhoto: "Failed to load selected photo",
    uploadWarning: "Warning",
    someFilesFailed: "Some files could not be uploaded",
    uploadError: "Upload error",
    uploadErrorDesc: "An error occurred while uploading files",
    loadingPhotos: "Loading photos...",
    photosFound: "Photos found",
    close: "Close",
    history: "History",
    uploading: "Uploading...",
    quality: "Quality",
    excellent: "Excellent",
    good: "Good",
    satisfactory: "Satisfactory",
    poor: "Poor",
    unknown: "Unknown",
    invalid: "Invalid",
    size: "Size",
    resolution: "Resolution",
    date: "Date",
    successfullyUploaded: "Successfully uploaded",
    filesFrom: "files from",
    files: "files",
    demoMode: "Demo Mode",
    demoModeDesc: "Photo history is not available in demo mode. Sign in to save photos.",
    myPhotos: "My Photos",
    viewAllPhotos: "View All Photos",
    uploadedPhotos: "Uploaded Photos",
    allPhotos: "All Photos",
    importedPhotos: "Imported Photos",
    uploaded: "Uploaded",
    imported: "Imported",
    noUploadedPhotos: "No uploaded photos",
    noImportedPhotos: "No imported photos",
    noUploadedPhotosDesc: "You haven't uploaded any photos yet",
    noImportedPhotosDesc: "You haven't imported any photos from competitor links yet",
    clearAll: "Clear All",
    clearAllConfirm: "Are you sure you want to clear all uploaded photos?",
    allPhotosCleared: "All photos cleared",
    qualityRelaxed: "Quality requirements relaxed - accepting most images",
    scrapedPhotos: "Scraped Photos",
    noScrapedPhotos: "No scraped photos",
    scrapePhotosToSeeThemHere: "Start scraping to see photos here",
    
    // Photo loaded notification
    photoLoaded: "photo loaded",
    photosLoaded: "photos loaded",
    
    // Image loading errors
    imageLoadError: "Image Load Error",
    imageLoadErrorDesc: "Failed to load image. The link may be expired or unavailable.",
  },
  ru: {
    // Navigation
    home: "Главная",
    studio: "Студия",
    docs: "Документация",
    login: "Вход",
    logout: "Выход",
    profile: "Профиль",
    
    // Home page
    heroTitle: "Превратите рекламу конкурентов в ваши победы",
    heroSubtitle: "Импортируйте проверенную рекламу, добавьте свой продукт, создайте варианты. Пропустите догадки, запустите то, что работает.",
    getStarted: "Начать",
    howItWorks: "Как это работает",
    step1Title: "Импорт рекламы конкурентов",
    step1Desc: "Вставьте URL из библиотеки рекламы Facebook для сбора успешных кампаний",
    step2Title: "Загрузите свой продукт",
    step2Desc: "Добавьте изображения вашего продукта, чтобы заменить товары конкурентов",
    step3Title: "Создание вариантов",
    step3Desc: "ИИ мгновенно создает множество вариантов рекламы",
    whyDifferent: "Почему отличается",
    whyDifferentDesc: "Большинство инструментов начинают с нуля. Мы начинаем с того, что уже конвертирует.",
    traditionalTools: "Традиционные инструменты",
    copyAdd: "COPY ADD",
    traditional1: "Начать с чистого листа",
    traditional2: "Угадать, что работает",
    traditional3: "Тестировать все",
    copyAdd1: "Начать с проверенной рекламы",
    copyAdd2: "Знать, что конвертирует",
    copyAdd3: "Улучшать победителей",
    
    // Auth
    email: "Электронная почта",
    password: "Пароль",
    confirmPassword: "Подтвердите пароль",
    passwordPlaceholder: "Минимум 6 символов",
    confirmPasswordPlaceholder: "Повторите пароль",
    demoLogin: "Демо вход",
    noAccount: "Нет аккаунта?",
    alreadyHaveAccount: "Уже есть аккаунт?",
    createAccount: "Создать аккаунт",
    signupDesc: "Зарегистрируйтесь для доступа к COPY ADD",
    signup: "Регистрация",
    signingUp: "Регистрация...",
    signupSuccess: "Проверьте почту для кода подтверждения",
    signupError: "Ошибка регистрации",
    signupFailed: "Не удалось зарегистрироваться",
    loginSuccess: "Успешный вход",
    passwordsDontMatch: "Пароли не совпадают",
    passwordTooShort: "Пароль должен содержать минимум 6 символов",
    invalidEmail: "Введите корректный email",
    fillAllFields: "Пожалуйста, заполните все поля",
    error: "Ошибка",
    success: "Успешно",
    continueWithGoogle: "Продолжить через Google",
    googleLoginError: "Не удалось войти через Google",
    
    // Verify Email
    verifyEmail: "Подтверждение Email",
    verifyEmailDesc: "Введите 6-значный код, отправленный на",
    verificationCode: "Код подтверждения",
    verify: "Подтвердить",
    verifying: "Проверка...",
    emailVerified: "Email подтвержден",
    verificationError: "Ошибка подтверждения",
    invalidCode: "Неверный код",
    enter6DigitCode: "Введите 6-значный код",
    verificationCodeSent: "Код подтверждения отправлен на почту",
    resendCode: "Отправить код повторно",
    codeSent: "Код отправлен",
    checkEmail: "Проверьте почту",
    backToLogin: "Вернуться ко входу",
    backToStudio: "Вернуться в студию",
    
    // Studio
    importAds: "Импорт рекламы конкурентов",
    importAdsDesc: "Вставьте URL библиотеки рекламы Facebook или ссылки на профили",
    pasteAdUrls: "Вставьте URL библиотеки рекламы Facebook или ссылки на профили",
    chooseFromHistory: "Выбрать из истории",
    noPreviousImports: "Нет предыдущих импортов",
    analyzingAds: "Анализ рекламы конкурентов...",
    authRequired: "Требуется авторизация",
    authRequiredDesc: "Пожалуйста, войдите в систему для доступа к студии",
    loggedOut: "Выход выполнен",
    loggedOutDesc: "Вы вышли из системы",
    or: "или",
    
    // Profile
    balance: "Баланс",
    username: "Имя пользователя",
    changePassword: "Сменить пароль",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmNewPassword: "Подтвердите новый пароль",
    saveChanges: "Сохранить изменения",
    changeAvatar: "Изменить аватар",
    referralCode: "Ваш реферальный код",
    referralDesc: "Поделитесь этим кодом для скидки 25%",
    copyCode: "Копировать код",
    codeCopied: "Код скопирован!",
    settings: "Настройки",
    editProfile: "Редактировать профиль",
    usernameExists: "Имя пользователя уже занято",
    usernameUpdated: "Имя пользователя обновлено",
    passwordUpdated: "Пароль успешно изменен",
    avatarUpdated: "Аватар обновлен",
    
    // Footer
    privacy: "Конфиденциальность",
    terms: "Условия",
    
    // Settings
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Темная",
    system: "Системная",
    lightTheme: "Светлая",
    darkTheme: "Темная",
    systemTheme: "Системная",
    snakeGame: "Анимация змейки",
    enableSnake: "Включить ретро-анимацию змейки",
    
    // Studio specific
    competitorAds: "Реклама конкурентов",
    scrapingCompetitorAds: "Сбор рекламы конкурентов...",
    adsImported: "Реклама импортирована",
    successfullyScraped: "Успешно собрано",
    competitorAdsCount: "рекламных объявлений конкурентов",
    uploadComplete: "Загрузка завершена",
    productsAdded: "товар(ов) добавлено",
    generatingVariants: "Создание вариантов",
    aiCreatingVariations: "ИИ создает варианты вашей рекламы...",
    addProduct: "Добавить товар",
    dragDropOrClick: "Перетащите или нажмите",
    dropHere: "Отпустите здесь",
    generate: "Создать с ИИ",
    import: "Импорт",
    importLink: "Импортировать ссылку",
    importLinkDesc: "Добавить новую ссылку для скрапинга рекламы конкурента",
    importUrlPlaceholder: "Введите URL рекламы конкурента",
    cancel: "Отмена",
    enterPrompt: "Напишите ваш промпт",
    selectAll: "Выбрать все",
    selected: "Выбрано",
    toPhotos: "к фото",
    toAllPhotos: "ко всем фото",
    describeChanges: "Опишите изменения...",
    clear: "Очистить",
    
    // Photo Editor
    photoEditor: "Редактор фотографии",
    promptForThisPhoto: "Промпт для этой фотографии",
    describeChangesForPhoto: "Опишите изменения для этой фотографии...",
    imageSettings: "Настройки изображения",
    brightness: "Яркость",
    contrast: "Контраст",
    saturation: "Насыщенность",
    reset: "Сбросить",
    done: "Готово",
    characters: "символов",
    
    // Home page stats
    activeUsers: "Активных пользователей",
    adsCreated: "Создано рекламы",
    successRate: "Успешность",
    
    // Photo History
    photoHistory: "История фотографий",
    photoHistoryDesc: "Выберите фотографию из вашей истории или загрузите новую",
    historyEmpty: "История пуста",
    historyEmptyDesc: "Загрузите первую фотографию, чтобы начать работу",
    selectPhoto: "Выбрать",
    deletePhoto: "Удалить",
    photoSelected: "Фотография выбрана",
    photoAddedToProject: "добавлена в проект",
    photoDeleted: "Фотография удалена",
    failedToDeletePhotos: "Не удалось удалить фотографии",
    failedToLoadPhoto: "Не удалось загрузить выбранную фотографию",
    uploadWarning: "Предупреждение",
    someFilesFailed: "Некоторые файлы не удалось загрузить",
    uploadError: "Ошибка загрузки",
    uploadErrorDesc: "Произошла ошибка при загрузке файлов",
    loadingPhotos: "Загрузка фотографий...",
    photosFound: "Найдено фотографий",
    close: "Закрыть",
    history: "История",
    uploading: "Загрузка...",
    quality: "Качество",
    excellent: "Отличное",
    good: "Хорошее",
    satisfactory: "Удовлетворительное",
    poor: "Плохое",
    unknown: "Неизвестно",
    invalid: "Невалидное",
    size: "Размер",
    resolution: "Разрешение",
    date: "Дата",
    successfullyUploaded: "Успешно загружено",
    filesFrom: "файлов из",
    files: "файлов",
    demoMode: "Демо-режим",
    demoModeDesc: "В демо-режиме история фотографий недоступна. Войдите в аккаунт для сохранения фотографий.",
    myPhotos: "Мои фотографии",
    viewAllPhotos: "Показать все",
    uploadedPhotos: "Загруженные фотографии",
    allPhotos: "Все фотографии",
    importedPhotos: "Импортированные фотографии",
    uploaded: "Загружено",
    imported: "Импорт",
    noUploadedPhotos: "Нет загруженных фотографий",
    noImportedPhotos: "Нет импортированных фотографий",
    noUploadedPhotosDesc: "Вы еще не загрузили фотографии на сайт",
    noImportedPhotosDesc: "Вы еще не импортировали фотографии из ссылок конкурентов",
    clearAll: "Очистить все",
    clearAllConfirm: "Вы уверены, что хотите очистить все загруженные фотографии?",
    allPhotosCleared: "Все фотографии очищены",
    qualityRelaxed: "Требования к качеству снижены - принимаем большинство изображений",
    scrapedPhotos: "Фотографии после скрапинга",
    noScrapedPhotos: "Нет скрапленных фотографий",
    scrapePhotosToSeeThemHere: "Запустите скрапинг, чтобы увидеть фотографии здесь",
    
    // Photo loaded notification
    photoLoaded: "Загружена 1 фотография",
    photosLoaded2to4: "Загружено {count} фотографии",
    photosLoaded: "Загружено {count} фотографий",
    
    // Image loading errors
    imageLoadError: "Ошибка загрузки изображения",
    imageLoadErrorDesc: "Не удалось загрузить изображение. Возможно, ссылка устарела или недоступна.",
  },
  de: {
    // Navigation
    home: "Startseite",
    studio: "Studio",
    docs: "Dokumentation",
    login: "Anmelden",
    logout: "Abmelden",
    profile: "Profil",
    
    // Home page
    heroTitle: "Verwandeln Sie Konkurrenzanzeigen in Ihre Gewinner",
    heroSubtitle: "Importieren Sie bewährte Anzeigen, überlagern Sie Ihr Produkt, generieren Sie Varianten. Überspringen Sie das Rätselraten, starten Sie was funktioniert.",
    getStarted: "Loslegen",
    howItWorks: "Wie es funktioniert",
    step1Title: "Konkurrenzanzeigen importieren",
    step1Desc: "Fügen Sie Facebook Ad Library URLs ein, um erfolgreiche Kampagnen zu scrapen",
    step2Title: "Laden Sie Ihr Produkt hoch",
    step2Desc: "Fügen Sie Ihre Produktbilder ein, um Konkurrenzartikel zu ersetzen",
    step3Title: "Varianten generieren",
    step3Desc: "KI erstellt sofort mehrere Anzeigenvarianten",
    whyDifferent: "Warum anders",
    whyDifferentDesc: "Die meisten Tools beginnen bei Null. Wir beginnen mit dem, was bereits konvertiert.",
    traditionalTools: "Traditionelle Tools",
    copyAdd: "COPY ADD",
    traditional1: "Mit leerer Leinwand beginnen",
    traditional2: "Raten, was funktioniert",
    traditional3: "Alles testen",
    copyAdd1: "Mit bewährten Anzeigen beginnen",
    copyAdd2: "Wissen, was konvertiert",
    copyAdd3: "Gewinner iterieren",
    
    // Auth
    email: "E-Mail",
    password: "Passwort",
    confirmPassword: "Passwort bestätigen",
    passwordPlaceholder: "Mindestens 6 Zeichen",
    confirmPasswordPlaceholder: "Passwort wiederholen",
    demoLogin: "Demo-Anmeldung",
    noAccount: "Noch kein Konto?",
    alreadyHaveAccount: "Bereits ein Konto?",
    createAccount: "Konto erstellen",
    signupDesc: "Registrieren Sie sich für den Zugriff auf COPY ADD",
    signup: "Registrieren",
    signingUp: "Registrierung läuft...",
    signupSuccess: "Überprüfen Sie Ihre E-Mail für den Bestätigungscode",
    signupError: "Registrierungsfehler",
    signupFailed: "Registrierung fehlgeschlagen",
    loginSuccess: "Erfolgreich angemeldet",
    passwordsDontMatch: "Passwörter stimmen nicht überein",
    passwordTooShort: "Passwort muss mindestens 6 Zeichen lang sein",
    invalidEmail: "Bitte geben Sie eine gültige E-Mail ein",
    fillAllFields: "Bitte füllen Sie alle Felder aus",
    error: "Fehler",
    success: "Erfolg",
    continueWithGoogle: "Mit Google fortfahren",
    googleLoginError: "Anmeldung mit Google fehlgeschlagen",
    
    // Verify Email
    verifyEmail: "E-Mail bestätigen",
    verifyEmailDesc: "Geben Sie den 6-stelligen Code ein, der gesendet wurde an",
    verificationCode: "Bestätigungscode",
    verify: "Bestätigen",
    verifying: "Überprüfung läuft...",
    emailVerified: "E-Mail bestätigt",
    verificationError: "Bestätigungsfehler",
    invalidCode: "Ungültiger Code",
    enter6DigitCode: "6-stelligen Code eingeben",
    verificationCodeSent: "Bestätigungscode per E-Mail gesendet",
    resendCode: "Code erneut senden",
    codeSent: "Code gesendet",
    checkEmail: "Überprüfen Sie Ihre E-Mail",
    backToLogin: "Zurück zur Anmeldung",
    backToStudio: "Zurück zum Studio",
    
    // Studio
    importAds: "Konkurrenzanzeigen importieren",
    importAdsDesc: "Facebook Ad Library URLs oder Profillinks einfügen",
    pasteAdUrls: "Facebook Ad Library URLs oder Profillinks einfügen",
    chooseFromHistory: "Aus Historie wählen",
    noPreviousImports: "Keine vorherigen Importe",
    analyzingAds: "Konkurrenzanzeigen werden analysiert...",
    authRequired: "Authentifizierung erforderlich",
    authRequiredDesc: "Bitte melden Sie sich an, um auf das Studio zuzugreifen",
    loggedOut: "Abgemeldet",
    loggedOutDesc: "Sie wurden abgemeldet",
    or: "oder",
    
    // Profile
    balance: "Guthaben",
    username: "Benutzername",
    changePassword: "Passwort ändern",
    currentPassword: "Aktuelles Passwort",
    newPassword: "Neues Passwort",
    confirmNewPassword: "Neues Passwort bestätigen",
    saveChanges: "Änderungen speichern",
    changeAvatar: "Avatar ändern",
    referralCode: "Ihr Empfehlungscode",
    referralDesc: "Teilen Sie diesen Code für 25% Rabatt",
    copyCode: "Code kopieren",
    codeCopied: "Code kopiert!",
    settings: "Einstellungen",
    editProfile: "Profil bearbeiten",
    usernameExists: "Benutzername bereits vergeben",
    usernameUpdated: "Benutzername aktualisiert",
    passwordUpdated: "Passwort erfolgreich geändert",
    avatarUpdated: "Avatar aktualisiert",
    
    // Footer
    privacy: "Datenschutz",
    terms: "Bedingungen",
    
    // Settings
    language: "Sprache",
    theme: "Thema",
    light: "Hell",
    dark: "Dunkel",
    system: "System",
    lightTheme: "Hell",
    darkTheme: "Dunkel",
    systemTheme: "System",
    snakeGame: "Schlangen-Animation",
    enableSnake: "Retro-Schlangenanimation aktivieren",
    
    // Studio specific
    competitorAds: "Konkurrenzanzeigen",
    scrapingCompetitorAds: "Konkurrenzanzeigen werden gesammelt...",
    adsImported: "Anzeigen importiert",
    successfullyScraped: "Erfolgreich gesammelt",
    competitorAdsCount: "Konkurrenzanzeigen",
    uploadComplete: "Upload abgeschlossen",
    productsAdded: "Produkt(e) hinzugefügt",
    generatingVariants: "Varianten werden erstellt",
    aiCreatingVariations: "KI erstellt Ihre Anzeigenvarianten...",
    addProduct: "Produkt hinzufügen",
    dragDropOrClick: "Ziehen & ablegen oder klicken",
    dropHere: "Hier ablegen",
    generate: "Mit KI erstellen",
    import: "Importieren",
    importLink: "Link importieren",
    importLinkDesc: "Einen neuen Link zum Scrapen von Konkurrenzanzeigen hinzufügen",
    importUrlPlaceholder: "URL der Konkurrenzanzeige eingeben",
    cancel: "Abbrechen",
    enterPrompt: "Schreiben Sie Ihren Prompt",
    selectAll: "Alle auswählen",
    selected: "Ausgewählt",
    toPhotos: "zu Fotos",
    toAllPhotos: "zu allen Fotos",
    describeChanges: "Änderungen beschreiben...",
    clear: "Löschen",
    
    // Photo Editor
    photoEditor: "Foto-Editor",
    promptForThisPhoto: "Prompt für dieses Foto",
    describeChangesForPhoto: "Änderungen für dieses Foto beschreiben...",
    imageSettings: "Bild-Einstellungen",
    brightness: "Helligkeit",
    contrast: "Kontrast",
    saturation: "Sättigung",
    reset: "Zurücksetzen",
    done: "Fertig",
    characters: "Zeichen",
    
    // Home page stats
    activeUsers: "Aktive Benutzer",
    adsCreated: "Erstellte Anzeigen",
    successRate: "Erfolgsrate",
    
    // Photo History
    photoHistory: "Fotogeschichte",
    photoHistoryDesc: "Wählen Sie ein Foto aus Ihrer Geschichte oder laden Sie ein neues hoch",
    historyEmpty: "Geschichte ist leer",
    historyEmptyDesc: "Laden Sie Ihr erstes Foto hoch, um zu beginnen",
    selectPhoto: "Auswählen",
    deletePhoto: "Löschen",
    photoSelected: "Foto ausgewählt",
    photoAddedToProject: "zum Projekt hinzugefügt",
    photoDeleted: "Foto gelöscht",
    failedToDeletePhotos: "Fotos konnten nicht gelöscht werden",
    failedToLoadPhoto: "Ausgewähltes Foto konnte nicht geladen werden",
    uploadWarning: "Warnung",
    someFilesFailed: "Einige Dateien konnten nicht hochgeladen werden",
    uploadError: "Upload-Fehler",
    uploadErrorDesc: "Beim Hochladen der Dateien ist ein Fehler aufgetreten",
    loadingPhotos: "Fotos werden geladen...",
    photosFound: "Fotos gefunden",
    close: "Schließen",
    history: "Geschichte",
    uploading: "Hochladen...",
    quality: "Qualität",
    excellent: "Ausgezeichnet",
    good: "Gut",
    satisfactory: "Befriedigend",
    poor: "Schlecht",
    unknown: "Unbekannt",
    invalid: "Ungültig",
    size: "Größe",
    resolution: "Auflösung",
    date: "Datum",
    successfullyUploaded: "Erfolgreich hochgeladen",
    filesFrom: "Dateien von",
    files: "Dateien",
    demoMode: "Demo-Modus",
    demoModeDesc: "Fotoverlauf ist im Demo-Modus nicht verfügbar. Melden Sie sich an, um Fotos zu speichern.",
    myPhotos: "Meine Fotos",
    viewAllPhotos: "Alle anzeigen",
    uploadedPhotos: "Hochgeladene Fotos",
    allPhotos: "Alle Fotos",
    importedPhotos: "Importierte Fotos",
    uploaded: "Hochgeladen",
    imported: "Importiert",
    noUploadedPhotos: "Keine hochgeladenen Fotos",
    noImportedPhotos: "Keine importierten Fotos",
    noUploadedPhotosDesc: "Sie haben noch keine Fotos hochgeladen",
    noImportedPhotosDesc: "Sie haben noch keine Fotos aus Wettbewerber-Links importiert",
    clearAll: "Alle löschen",
    clearAllConfirm: "Sind Sie sicher, dass Sie alle hochgeladenen Fotos löschen möchten?",
    allPhotosCleared: "Alle Fotos gelöscht",
    scrapedPhotos: "Gescrapte Fotos",
    noScrapedPhotos: "Keine gescrapten Fotos",
    scrapePhotosToSeeThemHere: "Starten Sie das Scraping, um Fotos hier zu sehen",
    qualityRelaxed: "Qualitätsanforderungen gelockert - akzeptieren die meisten Bilder",
    
    // Photo loaded notification
    photoLoaded: "Foto geladen",
    photosLoaded: "Fotos geladen",
    
    // Image loading errors
    imageLoadError: "Bildlade-Fehler",
    imageLoadErrorDesc: "Bild konnte nicht geladen werden. Der Link ist möglicherweise abgelaufen oder nicht verfügbar.",
  },
  pl: {
    // Navigation
    home: "Strona główna",
    studio: "Studio",
    docs: "Dokumentacja",
    login: "Zaloguj się",
    logout: "Wyloguj",
    profile: "Profil",
    
    // Home page
    heroTitle: "Zamień reklamy konkurencji w swoje zwycięstwa",
    heroSubtitle: "Importuj sprawdzone reklamy, nałóż swój produkt, generuj warianty. Pomiń zgadywanie, uruchom to, co działa.",
    getStarted: "Rozpocznij",
    howItWorks: "Jak to działa",
    step1Title: "Importuj reklamy konkurencji",
    step1Desc: "Wklej URL-e z biblioteki reklam Facebook, aby zebrać udane kampanie",
    step2Title: "Prześlij swój produkt",
    step2Desc: "Dodaj zdjęcia swojego produktu, aby zastąpić artykuły konkurencji",
    step3Title: "Generuj warianty",
    step3Desc: "AI natychmiast tworzy wiele wariantów reklam",
    whyDifferent: "Dlaczego inaczej",
    whyDifferentDesc: "Większość narzędzi zaczyna od zera. My zaczynamy od tego, co już konwertuje.",
    traditionalTools: "Tradycyjne narzędzia",
    copyAdd: "COPY ADD",
    traditional1: "Zacznij od pustego płótna",
    traditional2: "Zgaduj, co działa",
    traditional3: "Testuj wszystko",
    copyAdd1: "Zacznij od sprawdzonych reklam",
    copyAdd2: "Wiedz, co konwertuje",
    copyAdd3: "Iteruj zwycięzców",
    
    // Auth
    email: "E-mail",
    password: "Hasło",
    confirmPassword: "Potwierdź hasło",
    passwordPlaceholder: "Minimum 6 znaków",
    confirmPasswordPlaceholder: "Powtórz hasło",
    demoLogin: "Demo logowanie",
    noAccount: "Nie masz konta?",
    alreadyHaveAccount: "Masz już konto?",
    createAccount: "Utwórz konto",
    signupDesc: "Zarejestruj się, aby uzyskać dostęp do COPY ADD",
    signup: "Zarejestruj się",
    signingUp: "Rejestracja...",
    signupSuccess: "Sprawdź swoją pocztę e-mail dla kodu weryfikacyjnego",
    signupError: "Błąd rejestracji",
    signupFailed: "Nie udało się zarejestrować",
    loginSuccess: "Pomyślnie zalogowano",
    passwordsDontMatch: "Hasła nie pasują do siebie",
    passwordTooShort: "Hasło musi mieć co najmniej 6 znaków",
    invalidEmail: "Proszę wprowadzić poprawny e-mail",
    fillAllFields: "Proszę wypełnić wszystkie pola",
    error: "Błąd",
    success: "Sukces",
    continueWithGoogle: "Kontynuuj z Google",
    googleLoginError: "Nie udało się zalogować przez Google",
    
    // Verify Email
    verifyEmail: "Zweryfikuj e-mail",
    verifyEmailDesc: "Wprowadź 6-cyfrowy kod wysłany na",
    verificationCode: "Kod weryfikacyjny",
    verify: "Zweryfikuj",
    verifying: "Weryfikacja...",
    emailVerified: "E-mail zweryfikowany",
    verificationError: "Błąd weryfikacji",
    invalidCode: "Nieprawidłowy kod",
    enter6DigitCode: "Wprowadź 6-cyfrowy kod",
    verificationCodeSent: "Kod weryfikacyjny wysłany na e-mail",
    resendCode: "Wyślij kod ponownie",
    codeSent: "Kod wysłany",
    checkEmail: "Sprawdź swoją pocztę e-mail",
    backToLogin: "Powrót do logowania",
    backToStudio: "Powrót do studia",
    
    // Studio
    importAds: "Importuj reklamy konkurencji",
    importAdsDesc: "Wklej URL-e biblioteki reklam Facebook lub linki do profili",
    pasteAdUrls: "Wklej URL-e biblioteki reklam Facebook lub linki do profili",
    chooseFromHistory: "Wybierz z historii",
    noPreviousImports: "Brak poprzednich importów",
    analyzingAds: "Analiza reklam konkurencji...",
    authRequired: "Wymagana autoryzacja",
    authRequiredDesc: "Proszę się zalogować, aby uzyskać dostęp do studia",
    loggedOut: "Wylogowano",
    loggedOutDesc: "Zostałeś wylogowany",
    or: "lub",
    
    // Profile
    balance: "Saldo",
    username: "Nazwa użytkownika",
    changePassword: "Zmień hasło",
    currentPassword: "Obecne hasło",
    newPassword: "Nowe hasło",
    confirmNewPassword: "Potwierdź nowe hasło",
    saveChanges: "Zapisz zmiany",
    changeAvatar: "Zmień awatar",
    referralCode: "Twój kod polecający",
    referralDesc: "Udostępnij ten kod dla zniżki 25%",
    copyCode: "Kopiuj kod",
    codeCopied: "Kod skopiowany!",
    settings: "Ustawienia",
    editProfile: "Edytuj profil",
    usernameExists: "Nazwa użytkownika już zajęta",
    usernameUpdated: "Nazwa użytkownika zaktualizowana",
    passwordUpdated: "Hasło pomyślnie zmienione",
    avatarUpdated: "Awatar zaktualizowany",
    
    // Footer
    privacy: "Prywatność",
    terms: "Warunki",
    
    // Settings
    language: "Język",
    theme: "Motyw",
    light: "Jasny",
    dark: "Ciemny",
    system: "Systemowy",
    lightTheme: "Jasny",
    darkTheme: "Ciemny",
    systemTheme: "Systemowy",
    snakeGame: "Animacja węża",
    enableSnake: "Włącz retro animację węża",
    
    // Studio specific
    competitorAds: "Reklamy konkurencji",
    scrapingCompetitorAds: "Zbieranie reklam konkurencji...",
    adsImported: "Reklamy zaimportowane",
    successfullyScraped: "Pomyślnie zebrano",
    competitorAdsCount: "reklam konkurencji",
    uploadComplete: "Przesyłanie zakończone",
    productsAdded: "produkt(ów) dodano",
    generatingVariants: "Tworzenie wariantów",
    aiCreatingVariations: "AI tworzy warianty Twojej reklamy...",
    addProduct: "Dodaj produkt",
    dragDropOrClick: "Przeciągnij i upuść lub kliknij",
    dropHere: "Upuść tutaj",
    generate: "Generuj z AI",
    import: "Importuj",
    importLink: "Importuj link",
    importLinkDesc: "Dodaj nowy link do scrapowania reklam konkurencji",
    importUrlPlaceholder: "Wprowadź URL reklamy konkurencji",
    cancel: "Anuluj",
    enterPrompt: "Napisz swój prompt",
    selectAll: "Zaznacz wszystkie",
    selected: "Zaznaczone",
    toPhotos: "do zdjęć",
    toAllPhotos: "do wszystkich zdjęć",
    describeChanges: "Opisz zmiany...",
    clear: "Wyczyść",
    
    // Photo Editor
    photoEditor: "Edytor zdjęć",
    promptForThisPhoto: "Prompt dla tego zdjęcia",
    describeChangesForPhoto: "Opisz zmiany dla tego zdjęcia...",
    imageSettings: "Ustawienia obrazu",
    brightness: "Jasność",
    contrast: "Kontrast",
    saturation: "Nasycenie",
    reset: "Resetuj",
    done: "Gotowe",
    characters: "znaków",
    
    // Home page stats
    activeUsers: "Aktywni użytkownicy",
    adsCreated: "Utworzone reklamy",
    successRate: "Wskaźnik sukcesu",
    
    // Photo History
    photoHistory: "Historia zdjęć",
    photoHistoryDesc: "Wybierz zdjęcie z historii lub prześlij nowe",
    historyEmpty: "Historia jest pusta",
    historyEmptyDesc: "Prześlij pierwsze zdjęcie, aby rozpocząć",
    selectPhoto: "Wybierz",
    deletePhoto: "Usuń",
    photoSelected: "Zdjęcie wybrane",
    photoAddedToProject: "dodane do projektu",
    photoDeleted: "Zdjęcie usunięte",
    failedToDeletePhotos: "Nie udało się usunąć zdjęć",
    failedToLoadPhoto: "Nie udało się załadować wybranego zdjęcia",
    uploadWarning: "Ostrzeżenie",
    someFilesFailed: "Niektóre pliki nie mogły zostać przesłane",
    uploadError: "Błąd przesyłania",
    uploadErrorDesc: "Wystąpił błąd podczas przesyłania plików",
    loadingPhotos: "Ładowanie zdjęć...",
    photosFound: "Znaleziono zdjęć",
    close: "Zamknij",
    history: "Historia",
    uploading: "Przesyłanie...",
    quality: "Jakość",
    excellent: "Doskonała",
    good: "Dobra",
    satisfactory: "Zadowalająca",
    poor: "Słaba",
    unknown: "Nieznana",
    invalid: "Nieprawidłowa",
    size: "Rozmiar",
    resolution: "Rozdzielczość",
    date: "Data",
    successfullyUploaded: "Pomyślnie przesłane",
    filesFrom: "plików z",
    files: "plików",
    demoMode: "Tryb demo",
    demoModeDesc: "Historia zdjęć nie jest dostępna w trybie demo. Zaloguj się, aby zapisywać zdjęcia.",
    myPhotos: "Moje zdjęcia",
    viewAllPhotos: "Pokaż wszystkie",
    uploadedPhotos: "Przesłane zdjęcia",
    allPhotos: "Wszystkie zdjęcia",
    importedPhotos: "Zaimportowane zdjęcia",
    uploaded: "Przesłane",
    imported: "Zaimportowane",
    noUploadedPhotos: "Brak przesłanych zdjęć",
    noImportedPhotos: "Brak zaimportowanych zdjęć",
    noUploadedPhotosDesc: "Nie przesłałeś jeszcze żadnych zdjęć",
    noImportedPhotosDesc: "Nie zaimportowałeś jeszcze żadnych zdjęć z linków konkurentów",
    clearAll: "Wyczyść wszystkie",
    clearAllConfirm: "Czy na pewno chcesz wyczyścić wszystkie przesłane zdjęcia?",
    allPhotosCleared: "Wszystkie zdjęcia wyczyszczone",
    scrapedPhotos: "Zdjęcia po scrapingu",
    noScrapedPhotos: "Brak zdjęć po scrapingu",
    scrapePhotosToSeeThemHere: "Uruchom scraping, aby zobaczyć zdjęcia tutaj",
    qualityRelaxed: "Wymagania jakości złagodzone - akceptujemy większość obrazów",
    
    // Photo loaded notification
    photoLoaded: "zdjęcie załadowane",
    photosLoaded: "zdjęć załadowano",
    
    // Image loading errors
    imageLoadError: "Błąd ładowania obrazu",
    imageLoadErrorDesc: "Nie udało się załadować obrazu. Link może być nieaktualny lub niedostępny.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
