// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gehkormuxramehpxhdku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaGtvcm11eHJhbWVocHhoZGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mzg2NjYsImV4cCI6MjA2NDIxNDY2Nn0.2ic08B_Xl1WQ2N9EV6QtwYGI17fvri4j4ZEeGqC_FKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});